group: travis_latest

language: python

python:
    - 3.6

compiler:
    - g++
   
cache:
    ccache: true
    pip: true

before_install:
    - pip install --upgrade pip
    - pip install cython
    - pip install torch torchvision
    - pip install --upgrade torchvision

install:
    - pip install -e .

script:
    - python setup.py test

after_success:
    - codecov