group: travis_latest

language: python

python:
    - 3.6

compiler:
    - gcc
   
cache:
    ccache: true
    pip: true

install:
    - pip install --upgrade pip
    - pip install -e .

after_success:
    - codecov